openapi: 3.0.0
info:
  title: Payments of legal entities OpenAPI specification
  version: 0.0.1
paths:
  /Clients/GetStatus/{client_id}:
    get:
      summary: Find out the status by id
      tags:
        - Clients
      operationId: GETstatus
      parameters:
        - name: client_id
          in: path
          required: true
          description: client id
          schema:
            type: integer
            example: 123456789012345673
      responses:
        "200":
          description: Current status of the client
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Client"
  /Clients/Block/{client_id}:
    post:
      summary: Block client by id
      tags:
        - Clients
      parameters:
        - name: client_id
          in: path
          required: true
          description: client id
          schema:
            type: integer
            example: 123456789012345673
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Client"
      responses:
        "200":
          description: Success
  /Clients/UnBlock/{client_id}:
    delete:
      summary: UnBlock client by id
      tags:
        - Client
      parameters:
        - name: client_id
          in: path
          required: true
          description: client id
          schema:
            type: integer
            example: 123456789012345673
      responses:
        "200":
          description: Unblocked
          content:
            application/json: {}
components:
  schemas:
    Client:
      type: object
      required:
        - client_id
        - status
      properties:
        client_id:
          type: integer
          example: 123456789012345673
        status:
          type: string
          enum:
            - Block_fraud
            - Block_temporary
    Clients:
        type: array
        items:
          $ref: "#/components/schemas/Clients"




